### ISSUE TITLE
Navigation Dropdown broken in Edge

### ISSUE THREAD

**Issue by maqalexh** [maqsoftware/MAQSoftware#175]
![image](https://user-images.githubusercontent.com/30702470/43744758-71397788-9990-11e8-8878-548f0733bb91.png)
Image of the ABout Dropdown in Edge. Oddly spaced, lines have bullets.

![image](https://user-images.githubusercontent.com/30702470/43744834-c6fdcc00-9990-11e8-9fd8-a02bd850a895.png)
Correct display in Chrome

**Comment by MAQ-AkshayaK** [comment]
this is an existing bug in Edge. Refer the link below
https://github.com/webhintio/webhint.io/issues/210
It has been handled
