### ISSUE TITLE
Fix LinkedIn Share Links on Interactive Reports pages

### ISSUE THREAD

**Issue by maqalexf** [maqsoftware/MAQSoftware#202]
LinkedIn share buttons on Route Map, Election Map, and National Achievement Survey 2017 all show Inc 5000 link instead of links to the correct Interactive Reports.
![2018-08-20 15_59_25-window](https://user-images.githubusercontent.com/36492646/44371137-53a06080-a492-11e8-925c-c8d4419c9773.png)

**Comment by MAQ-AkshayaK** [comment]
fixed
