### ISSUE TITLE
Fix grammar errors on Recognitions page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#204]
https://maqsoftware.com/about/recognitions

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Change "Recognitions" to "Accolades"

In the first section, Under Armour is misspelled as "Under Armor" (company name is weird spelling).

In the Microsoft Gold Partner section, there needs to be a comma after "Application Development."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
