### ISSUE TITLE
Fix grammar errors on Who We Are page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#205]
https://maqsoftware.com/about/whoweare

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

In the "Reducing Cycle Time..." section under the gear, there should be a comma after "deploy."

In the "Why do our clients choose to work with us?" section under "reduced time to market," there should be a comma after "knowledge."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
