### ISSUE TITLE
Fix grammar errors on Education page.

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#206]
https://maqsoftware.com/about/whoweare

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Hyphenate "low income families" (low-income) in the first description under "India Education Initiative."

In the final paragraph on the page, the second sentence should read as follows: "To start, MAQ Software will provide three-year grants to leading NGOs to sponsor research at IITs, NITs, IIITs, and IIMs and adopt solutions from them."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
