### ISSUE TITLE
Fix grammar errors on the Careers page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#207]
https://maqsoftware.com/careers

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

In the description below "Why do A-players choose to work with us," the final sentence needs an article. Sentence should probably read as follows: "Our company has the highest density in the industry of Agile Certified Practitioners (ACP) from the Project Management Institute (PMI)."

In the final bullet point under "Company culture," "fast paced" should be hyphenated ("fast-paced").

Given the formatting of the information around it, this can potentially be ignored, but there is no real reason for the word "e-mail" to be capitalized following "for positions in Redmond" and "for positions in India." Ideally, lowercase the "e."

The formatting of "RedmondJobs@MAQSoftware.com" and "IndiaJobs at MAQSoftware.com" should be the same ("IndiaJobs@MAQSoftware.com").

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
