### ISSUE TITLE
Fix grammar errors on Power BI Best Practices Guide

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#208]
https://maqsoftware.com/expertise/powerbi/power-bi-best-practices

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

In section 9, an article is needed. The third sentence should read as follows: "If a custom visual performs poorly, consider changing it to a different visual."

In section 11, the description after the colon should read as follows: "one gets the data, and the other fetches selection details."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
