### ISSUE TITLE
Fix grammar errors on Azure Architecture Best Practices Guide

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#209]
https://maqsoftware.com/expertise/cloudtransformation/azure-architecture-best-practices

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

In the third paragraph of section 1, "business-hours" should not be hyphenated (at line break).

In the next sentence, "business-hours" is hyphenated again. Given that "business hours" is referenced later without a hyphen, I would change this sentence to the following: "The environments automatically start again before business hours resume."

In the final sentence of the third paragraph, the verb tense is changed from present tense to past tense. I would recast the sentence to read as follows: "Depending on usage patterns, Azure subscription costs can be reduced by 20% to 30% by turning VMs off outside of business hours." Doing so, however, does introduce passive voice.

In the third section, the final sentence of the first paragraph should read as follows: "This also allows for high availability, even when a model is being processed."

The phrase immediately following the first bullet point in section 4 should read as follows: "Static resource classes, which are well suited for increased concurrency on fixed data sets."

The phrase following the second bullet point in section 4 should read as follows: "Dynamic resource classes, which are well suited for data sets that are growing in size and improving performance as the service level is scaled up."

In the next sentence, the comma between "complex" and "but" should be removed.

In the final paragraph of section 4, eliminate the word "sized" in "fixed sized datasets."

In the second sentence of section 6, place a comma after "model."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
