### ISSUE TITLE
Fix grammar errors on Azure Security Best Practices

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#210]
https://maqsoftware.com/expertise/cloudtransformation/azure-security-best-practices

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

The first sentence of the second paragraph in the introduction should be recast as follows: "Eight years ago during the Azure public preview, we assured our customers and management that our cloud implementations were secure."

In the third sentence, "well-understood" should not be hyphenated.

In section 1, the word "the" should be placed between "check" and "security."

In section 2, "cyber-attacks" does not need to be hyphenated.

In section 7, there needs to be a comma after "e.g."

In section 10, eliminate "-based."

In section 13, recast the second sentence as follows: "Additional backups are created during system software upgrades when new versions of applications are installed or, sometimes, just in case."

**Comment by maqryane** [comment]
In section 4, there should be double quotes around both instances of "Least Privilege."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
