### ISSUE TITLE
Fix grammar errors on Interactive Power BI Reports (main page)

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#211]
https://maqsoftware.com/resources/interactive-reports

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Description under the National Achievement Survey 2017 should read as follows: "Lets users visualize the data of the National Achievement Survey using the highly interactive features of the Power BI."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
