### ISSUE TITLE
Fix grammar errors on Case Studies (main page) and revise titles

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#212]
https://maqsoftware.com/case-studies

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Delete the "a" from the title of the airplane graphic ("Custom Power BI Visual Allows a Travel Company to Analyze Flight Route Performance").

Title changes:

The following changes are complicated by the fact that the titles of these case studies are used on other parts of the site. Changes made to the titles on this page will need to be reflected in the Facebook description, the LinkedIn description, the Twitter description, the section of the expertise page on which the case studies are featured (https://maqsoftware.com/expertise/powerbi), and the case studies's individual page. Links will be provided to the appropriate case study page below. (Note: Some of these changes may already be reflected in the site.)

<img width="936" alt="metatags photo" src="https://user-images.githubusercontent.com/42557872/44434637-1bb41e80-a561-11e8-94b8-09bf63f76b35.PNG">

Change "Using AI to Determine the Validity of Customer Engagement for Incentive Payout" to "Using AI to Streamline Incentive Payouts"

https://maqsoftware.com/case-studies/incentive-payment

Change "Using AI Sentiment Analysis to Evaluate Feedback from a Large User Conference" to "Sentiment Analysis Helps Evaluate Conference Feedback"

https://maqsoftware.com/case-studies/sentiment-analysis

Change "Using AI to Evaluate Intent to Purchase New Software Products and Services" to "Generating Sales Leads with AI"

https://maqsoftware.com/case-studies/purchase-intent

Change "Leading Retailer Tracks Promotion Results in Real-time to Maximize Sales" to "Boosting Black Friday Sales with AI"

https://maqsoftware.com/case-studies/black-friday

Change "Collaborative, Cloud-Based Policy Portal Allows Software Company to Stay Informed of Global Affairs" to "Software Company Monitors Global Affairs with Cloud-Based Policy Portal"

https://maqsoftware.com/case-studies/policy-database

Change "Scalable Azure Solution Aggregates Marketing Data from Disparate Database Sources to Provide Customer-Specific Promotional Offers" to "Consolidate Data on the Cloud for Better Marketing"

https://maqsoftware.com/case-studies/marketing-data

Change "To Improve Productivity, a Leading Software Company Migrates Distribution Channel Incentive Application to the Microsoft Cloud" to "Software Company Improves Incentive Tracking by Migrating to Microsoft Cloud"

https://maqsoftware.com/case-studies/incentive-tracking

Change "Using AI with Video Analysis to Determine Real-Time Audience Emotions from Facial Expressions" to "AI Video Analysis Determines Real-Time Audience Emotions from Facial Expressions"

https://maqsoftware.com/case-studies/emotion-analyzer

Change "Leading Worldwide Retail Chain Uses AI to Automate Customer Feedback, Reducing Costs and Improving Customer Satisfaction" to "Retailer Reduces Costs by Automating Customer Feedback"

https://maqsoftware.com/case-studies/return-themes

**Comment by MAQHatimD** [comment]
Require confirmation on the title changes:
Do we need to update the description of the meta tag (og:description, twitter:description) or we need to update title of the meta tag (og:title, twitter:title) based on the titles of the case studies.

**Comment by maqryane** [comment]
The title stays the same on all metatags. Just update the description metatag (og:title, twitter:title).

**Comment by MAQ-AkshayaK** [comment]
Update in pull request #253
