### ISSUE TITLE
GIFs no longer appear in modal "learn more" window

### ISSUE THREAD

**Issue by maqalexf** [maqsoftware/MAQSoftware#214]
Page
[Power BI Expertise](https://maqsoftware.com/expertise/powerbi)
 
**Describe the problem**
GIFs showing custom Power BI visual usage no longer appear in the modal windows when clicking on the Learn More button from the custom visuals carousel on the Power BI expertise page.
 
**To Reproduce**
1. Go to https://maqsoftware.com/expertise/powerbi
2. Go to the Power BI custom visuals carousel
3. Mouse over a visual and click "Learn More"
 
**Expected behavior**
GIFs used to appear that showed the custom visual being used
 
**Screenshots**
![no-gif](https://user-images.githubusercontent.com/36492646/44439708-9f7a0500-a579-11e8-9700-4e69209c9b81.png)
 
**Test environment (please complete the following information):**
 - OS: Windows
 - Browser: All

**Comment by MAQ-AkshayaK** [comment]
fixed
