### ISSUE TITLE
Fix grammar errors on Power BI Expertise page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#216]
https://maqsoftware.com/expertise/powerbi

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Delete the "a" from the title of the airplane graphic at the top of the page ("Custom Power BI Visual Allows a Travel Company to Analyze Flight Route Performance").

Delete the "a" from the title of the airplane graphic in the Case Studies section of the page ("Custom Power BI Visual Allows a Travel Company to Analyze Flight Route Performance").

Hyphenate "third party" in the description of the case study titled "Customer Feedback Directly Integrated into Microsoft Power BI."

Change the description of the next case study to read as follows: "Using Power BI allows any website visitor to interact with business growth data."

Hyphenate "state of the art" in the description of the case study titled "Boosting Black Friday Sales with AI." (It should now read as follows: "MAQ Software implements a state-of-the-art Azure and Power BI solution to report sales.")

Change the description of the next case study ("Consolidate Data for Better Marketing") to read as follows: "MAQ Software delivers state-of-the-art solution to facilitate revenue growth for software company."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
