### ISSUE TITLE
Fix grammar errors on Case Study: Custom Power BI Global Filter Makes Creating Reports Easy page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#217]
https://maqsoftware.com/case-studies/global-filter

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Recast the "Solution" statement to read as follows: "We created a custom app that tailors users’ Power BI experience to their individual needs, allowing for easy navigation and the creation of custom reports."

Change the semicolon after "Power BI" in the description of Figure 2 to a colon. 

In the description under Figure 3, change the sentence to read as follows: "For example, a user can select a filter to only show data from the fiscal year 2017."

Change the next sentence to read as follows: "Once applied, only data from 2017 will be shown on all reports."

Remove the comma after "reports" in the next sentence.

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
