### ISSUE TITLE
Fix grammar errors on the Case Study: Custom Power BI Visual Allows a Travel Company... page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#218]
https://maqsoftware.com/case-studies/route-analytics

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Delete the "a" from the title (should now read as "Custom Power BI Visual Allows Travel Company to Analyze Flight Route Performance").

Change the "s" in "Coming Soon" (located to the right of "Try it Live" at the top of the page) to lowercase.

Place a comma after "KPIs." "KPIs" is located in the third sentence of the first paragraph entitled "Business Case."

Place a comma after "travel." "Travel" is located in the first sentence of the second paragraph entitled "Business Case." 

Place a comma after "data" (located in the first bullet point beneath "Key Challenges"). 

Hyphenate "one step" in the first sentence of the "Business Outcome" section.

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
