### ISSUE TITLE
Fix grammar errors on Case Study: Reduce Cloud Expenses... page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#219]
https://maqsoftware.com/case-studies/cost-optimization

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Change the word "more" to "higher" in the second sentence of the second paragraph in the "Business Case" section.

Change "under-utilized" to "underutilized" in the second bullet point of the "Key Challenges" section.

Change the second bullet point of the "Key Highlights" section to read as follows: "Automated allocation of resources to reduce costs."

Change the final sentence of the "Key Highlights" section to read as follows: "We also implemented best practices including automation scripts for turning off virtual machines outside of business hours and reviewing and decommissioning servers periodically, automation scripts to downgrade server usage on weekends, and automated daily Power BI reports for tracking cloud expenditures."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
