### ISSUE TITLE
Fix grammar errors on Case Study: Automatically Check Power BI Reports for Critical Errors page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#220]
https://maqsoftware.com/case-studies/health-check

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Change "licensed units" in the first sentence to "licensing units."

Recast first sentence of second paragraph to read as follows: "Support teams spend hours manually checking reports to make sure they load quickly and are free of glitches."

Change the next sentence to read as follows: "If the team finds errors, they contact the developers and hope there will be enough time to resolve any issues before the next review meeting." 

In the paragraph beneath the bullet points of "Key Highlights," change the first sentence to read as follows: "Setup of the Power BI health check solution requires the user to link all Power BI reports that need monitoring."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
