### ISSUE TITLE
Fix grammar errors on Case Study: Publishing Interactive Analytics to the Web Has Never Been Easier page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#221]
https://maqsoftware.com/case-studies/inc-5000

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Change the subtitle to read as follows: "Using Power BI allows any website visitor to interact with business growth data."

Change the third sentence in the first paragraph of the "Business Case" section to read as follows: "The Inc. list includes statistics about each company, including the company's previous year's revenue, industry, year founded, 3-year sales growth rate, number of employees, and location."

Change the second sentence of the second paragraph to read as follows: "Our analysis needed to be publicly accessible without requiring the installation and maintenance of additional servers."

Change the second bullet point of the "Key Challenges" section to read as follows: "Create a shared report without writing new code or putting extra load on the web server."

Change the first bullet point beneath "Key Highlights" to read as follows: "Pulls data from the online data source and generates report with zero html coding."

Add the words "which is" after "Power BI report" (second bullet point of the "Key Highlights" section).

Eliminate the comma after "search box" in the third sentence in the description below Figure 2.

Change "make" in the first sentence beneath figure 3 to "made."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
