### ISSUE TITLE
Fix grammar errors on Case Study: Customer Feedback Directly Integrated... page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#222]
https://maqsoftware.com/case-studies/feedback-solution

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

In the subtitle, "third party" should be hyphenated ("third-party"). 

In the second sentence of the description of Figure 1, "photo" should be changed to "photos."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
