### ISSUE TITLE
Fix grammar errors on Case Study: Examine Election Results... page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#223]
https://maqsoftware.com/case-studies/election-map

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Remove the comma after "winners" in the third bullet point in the "Business Case" section. 

Hyphenate "easy to use" in the first bullet point in the "Key Challenges" section ("easy-to-use").

Remove the comma after "Republican candidate" in the first sentence after the bulleted list.

Add "and" after "Republican" in the next sentence. (Sentence should read: "For example, clicking once on Washington state converts it to Republican, and clicking again changes the state to Democrat."

Remove the word "individual" in the first bullet point in the "Outcome Highlights" section.

Change "pre-configurable" to "preconfigured" in the final bullet point on the page.

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
