### ISSUE TITLE
Fix grammar errors on Case Study: Machine Learning Helps Prioritize Customer Support page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#224]
https://maqsoftware.com/case-studies/prioritizing-support

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

In the fifth sentence of the second paragraph, change "non-urgent" to "nonurgent" and remove the word "other" along with the comma that follows it. Then, change "higher-priority" to "high-priority."

In the second bullet point in the "Key Highlights" section, change "pre-process" to "preprocess."

In the next bullet point, add the word "a" before "Feature Hashing algorithm."

In the second sentence after figure 1, change "pre-processed" to "preprocess."

In the first sentence of the second paragraph after figure 1, remove the comma after "requests" and add the word "by."

In the next sentence, change the word "request" to "requests." 

Change the sentence of the second bullet point under "Outcome Highlights" to read as follows: "Prioritized higher seniority customers by addressing the most critical needs first."

Change the third bullet point to read as follows: "Support tickets are now assigned based on engineer expertise."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
