### ISSUE TITLE
Fix grammar errors on Case Study: "Using AI to Determine the Validity of Customer Engagement..." page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#225]
https://maqsoftware.com/case-studies/incentive-payment

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Recast the second sentence of the second paragraph within the "Business Case" section to read as follows: "Currently, verifying POE documents is a time-consuming manual process.

In the second sentence following figure 1, change "pre-processed" to "preprocessed." 

In the second paragraph after figure 1, add the word "a" after "using."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
