### ISSUE TITLE
Fix grammar errors on Case Study: Using AI to Identify Businesses for Event Marketing page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#226]
https://maqsoftware.com/case-studies/targeted-marketing

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

In the second sentence of the first paragraph of the "Business Case" section, change the "/" to a comma and add a space as appropriate. Then, put a comma directly after seminars.

In the first bullet point of the "Key Highlights" section, replace "pre-process" with "preprocess."

In the third sentence following Figure 1, replace "pre-processing" with "preprocessing."
Change the first sentence of the "Business Outcome" section to the following: "Using ML categorization, marketing managers now categorize prospective customers as “hot,” “warm,” or “cold” and focus marketing efforts on the segments that have a high conversion probability."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
