### ISSUE TITLE
Fix grammar errors on Case Study: Sentiment Analysis Helps Evaluate Conference Feedback page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#227]
https://maqsoftware.com/case-studies/sentiment-analysis

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

In the first sentence of the third paragraph in the "Business Case" section,  "time consuming" should be hyphenated ("time-consuming).

In the next sentence, "real time" should also be hyphenated ("real-time").

Add periods to the end of all the bullet points in the "Key Highlights" section. 

Add "a" after "is" in the second sentence of the first paragraph of the "Key Highlights" section ("N-gram is a probabilistic..."). 

In the first sentence of the second paragraph, add the word "the" after "used" ("We used the Stanford Core NLP algorithm...").

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
