### ISSUE TITLE
Fix grammar errors on Case Study: Manufacturer Uses AI Recommendation System... page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#228]
https://maqsoftware.com/case-studies/intelligent-recommendation

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Recast subtitle sentence to what follows: "MAQ Software implements a product recommendation engine for gaming hardware manufacturer allowing buyers to easily customize products."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
