### ISSUE TITLE
Fix grammar errors on Case Study: Using AI to Evaluate Intent to Purchase... page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#229]
https://maqsoftware.com/case-studies/purchase-intent

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

In the first sentence of the third paragraph of the "Business Case" section, replace the word "with" with "Due to"

In the first bullet point in the "Key Highlights" section, replace "pre-process" with "preprocess."

In the second sentence of the first paragraph of the "Key Highlights" section, replace "pre-process" with "preprocess." Then, delete the comma that followed "pre-processing."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
