### ISSUE TITLE
Fix grammar errors Case Study: Boosting Black Friday Sales with AI page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#230]
https://maqsoftware.com/case-studies/black-friday

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

In the third sentence of the second paragraph, change "real-time" to "real time."

In the first sentence of the third paragraph, change "time consuming" to "time-consuming." 

In the next sentence, change "real time" to "real-time"

In the first sentence of the second paragraph below Figure 1, add the word "the" after the word "in."

In the first sentence of the section entitled "Business Outcome," hyphenate "up to the minute" (it should look like "up-to-the-minute").

Recast the next sentence to read as follows: "The retailer no longer relies on traditional databases, which would take days to process the needed information."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
