### ISSUE TITLE
Fix grammar errors on Case Study: Collaborative, Cloud-Based Policy Portal...

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#231]
https://maqsoftware.com/case-studies/policy-database

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

In the second sentence in the first paragraph beneath Figure 1, change the word "which" to the word "that"

In the final sentence of the first paragraph beneath Figure 1, add the word "the" after "in"

In the final sentence of the third paragraph beneath Figure 1, recast the sentence as follows: "Based on keywords, Cognitive Services pulls relevant news from Bing, which is updated daily."

Recast the second sentence in the section entitled "Business Outcome" as follows: "The database minimizes the risk of policy violations, which could cost the company millions of dollars."

In the first bullet point beneath "Outcome Highlights," recast the sentence as follows: "Saved time by creating a searchable central repository for all current policy documents."

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
