### ISSUE TITLE
Fix grammar errors on Case Study: Consolidate Data for Better Marketing page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#232]
https://maqsoftware.com/case-studies/marketing-data

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

In the subtitle, "state of the art" needs to be hyphenated ("state-of-the-art").

In the third sentence of the second paragraph within the "Business Case" section, replace the word "on" with "in"

In the third paragraph of the Business Case section, hyphenate "easy to understand" ("easy-to-understand").

In the third bullet point beneath "Key Challenges," add the word "a" after the word "to."

In the first bullet point beneath "Key Highlights," add the word "and" after "static files"

In the next bullet point, hyphenate "easy to understand" ("easy-to-understand"). 

In the first sentence of the section entitled "Business Outcome," remove the comma after "together" and add the word "by." Then, hyphenate "easy to interpret ("easy-to-interpret"). 

In the next sentence, a comma needs to be placed after "on."

In the third bullet point beneath "Outcome Highlights," hyphenate "easy to interpret" ("easy-to-interpret").

**Comment by MAQ-AkshayaK** [comment]
Updated and merged
