### ISSUE TITLE
Fix grammar errors on Case Study: AI Video Analysis Determines Real-Time Audience... page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#246]
https://maqsoftware.com/case-studies/emotion-analyzer

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Add a comma after "frames" in the first sentence below Figure 1.

**Comment by MAQ-AkshayaK** [comment]
Update in pull request #253
