### ISSUE TITLE
Fix grammar errors on Case Study: Retailer Reduces Costs... page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#247]
https://maqsoftware.com/case-studies/return-themes

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

In the second sentence of the section entitled "Business Case," "first party" should be hyphenated ("first-party").

In the fourth sentence in the second paragraph of the same section, "first party" should be hyphenated.

In the third sentence of the third paragraph of the section entitled "Solution," "auto-correct" should not be hyphenated ("autocorrect"). 

Recast the second sentence of the section entitled "Business Outcome" to read as follows: "Customers were returning products either because they had found a lower price elsewhere or because they were experiencing hardware failures."

Recast the second sentence of the second paragraph of the "Business Outcome" section to read as follows: "By pinpointing problem areas, the client was able to save thousands of man-hours and potentially millions of dollars by reducing manufacturing errors and refurbishment costs."

**Comment by MAQ-AkshayaK** [comment]
Update in pull request #253
