### ISSUE TITLE
Fix grammar errors on Artifical Intelligence Expertise page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#248]
https://maqsoftware.com/expertise/artificialintelligence

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

The second sentence beneath the main header on the page should read as follows: "It eliminates routine tasks, continually improves processes, and allows you to focus on creativity and growth."

**Comment by MAQ-AkshayaK** [comment]
Update in pull request #253
