### ISSUE TITLE
Fix grammar errors on Data Management Expertise page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#249]
https://maqsoftware.com/expertise/datamanagement

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Recast the first sentence under the header to read as follows: "We deliver data management solutions, including multiple database applications for Fortune 500 companies, using data from a range of sales and marketing databases."

Under the "Data Warehousing" tab, add a comma after "Medium Business Impact" (third bullet point of "Deeper Insights").

Under the "Optimization" tab, add the word "and" after "hierarchy queues," (fourth bullet point of "Operate Efficiently").

Under the "Azure Data Lake" tab, recast the first bullet point beneath "Data Manipulation" to read as follows: "We create custom reducers that enhance the out-of-box Azure Data Lake operators to perfrom complicated business logic."

Change "Real Time Power BI Reports" to "Real-Time Power BI Reports"

Change the first bullet point beneath "Real Time Power BI Reports": the word "the" needs to follow "push."

**Comment by MAQ-AkshayaK** [comment]
Update in pull request #253
