### ISSUE TITLE
Fix grammar errors on Cloud Transformation Expertise page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#250]
https://maqsoftware.com/expertise/cloudtransformation

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

Recast the second sentence beneath the main header to read as follows: "We can help you optimize and manage your cloud solutions by reducing the amount of time required to manage, maintain and deploy your data."

Change "low cost," beneath the "Custom Applications" bullet point, to "low-cost."

**Comment by MAQ-AkshayaK** [comment]
Update in pull request #253
