### ISSUE TITLE
Fix grammar errors on App Development Expertise page

### ISSUE THREAD

**Issue by maqryane** [maqsoftware/MAQSoftware#251]
https://maqsoftware.com/expertise/appdevelopment

All of the subsequent problems are simply editorial errors. The following descriptions will direct you to the error and provide the solution.

In the main header, change "cutting edge" to "cutting-edge."

Under the Windows & SharePoint Apps tab, change the Timesheet section as follows: "Keeps track of effort spent by employees on various components of a project. Creates custom dashboards and transforms their underlying databases."

Under the "Office Apps" tab, delete the word "have" in the first section of the description.

In the "TaskIT" bullet point, change "to do" to "to-do."

In the Unit Converter bullet point, change "for" to "to"

**Comment by MAQ-AkshayaK** [comment]
Update in pull request #253
